security:
  password_hashers:
    Symfony\Component\Security\Core\User\InMemoryUser: plaintext

  providers:
    shopwho_admin:
      memory:
        users:
          admin:
            password: '%env(ADMIN_PASSWORD)%'
            roles: ['ROLE_ADMIN']

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: shopwho_admin
      http_basic:
        realm: 'Shopwho Admin'

  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
