security:
  password_hashers:
    App\Entity\User: 'auto'

  providers:
    shopwho_users:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: shopwho_users

      form_login:
        login_path: admin_login
        check_path: admin_login
        enable_csrf: true
        default_target_path: admin_product_index

      logout:
        path: admin_logout
        target: app_home

  access_control:
    - { path: ^/admin/login$, roles: PUBLIC_ACCESS }
    - { path: ^/admin, roles: ROLE_ADMIN }
