security:
  password_hashers:
    App\Entity\User: 'auto'

  providers:
    shopwho_users:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: shopwho_users

      form_login:
        login_path: app_login
        check_path: app_login
        enable_csrf: true
        default_target_path: app_profile

      logout:
        path: app_logout
        target: app_home

  access_control:
    - { path: ^/connexion$, roles: PUBLIC_ACCESS }
    - { path: ^/admin/login$, roles: PUBLIC_ACCESS }
    - { path: ^/admin/logout$, roles: PUBLIC_ACCESS }
    - { path: ^/profil(?:/|$), roles: ROLE_USER }
    - { path: ^/admin, roles: ROLE_ADMIN }
