<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260823230000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add verified product reviews with restricted user and product deletion';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE product_review (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, product_id INT NOT NULL, external_ref VARCHAR(180) DEFAULT NULL, rating INT NOT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id), CONSTRAINT chk_product_review_rating CHECK (rating >= 1 AND rating <= 5))');
        $this->addSql('CREATE INDEX IDX_1B3FC062A76ED395 ON product_review (user_id)');
        $this->addSql('CREATE INDEX IDX_1B3FC0624584665A ON product_review (product_id)');
        $this->addSql('CREATE INDEX idx_product_review_created_at ON product_review (created_at)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1B3FC062B445906B ON product_review (external_ref)');
        $this->addSql('CREATE UNIQUE INDEX uniq_product_review_user_product ON product_review (user_id, product_id)');
        $this->addSql('ALTER TABLE product_review ADD CONSTRAINT fk_product_review_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_review ADD CONSTRAINT fk_product_review_product FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE product_review');
    }
}
