<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260823150000 extends AbstractMigration
{
    public function getDescription(): string { return 'Create behavioral tracking event table'; }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE tracking_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, visitor_id VARCHAR(64) NOT NULL, session_id VARCHAR(64) NOT NULL, event_type VARCHAR(50) NOT NULL, product_id INT DEFAULT NULL, metadata JSON NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_tracking_session_time ON tracking_event (session_id, occurred_at)');
        $this->addSql('CREATE INDEX idx_tracking_type_time ON tracking_event (event_type, occurred_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE tracking_event');
    }
}
