<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260910194613 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE ab_experiment (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              experiment_key VARCHAR(120) NOT NULL,
              name VARCHAR(160) NOT NULL,
              status VARCHAR(20) NOT NULL,
              traffic_percentage SMALLINT NOT NULL,
              starts_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3DBAEE874F47DFC ON ab_experiment (experiment_key)');
        $this->addSql(<<<'SQL'
            CREATE TABLE ab_experiment_variant (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              variant_key VARCHAR(80) NOT NULL,
              name VARCHAR(160) NOT NULL,
              weight INT NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              experiment_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_FDF35E0BFF444C8 ON ab_experiment_variant (experiment_id)');
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_ab_experiment_variant_key ON ab_experiment_variant (experiment_id, variant_key)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              ab_experiment_variant
            ADD
              CONSTRAINT FK_FDF35E0BFF444C8 FOREIGN KEY (experiment_id) REFERENCES ab_experiment (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ab_experiment_variant DROP CONSTRAINT FK_FDF35E0BFF444C8');
        $this->addSql('DROP TABLE ab_experiment');
        $this->addSql('DROP TABLE ab_experiment_variant');
    }
}
