<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260827152300 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE special_offer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(160) NOT NULL, content TEXT NOT NULL, cta_label VARCHAR(80) DEFAULT NULL, target_url VARCHAR(500) DEFAULT NULL, placement VARCHAR(20) NOT NULL, background_color VARCHAR(7) NOT NULL, text_color VARCHAR(7) NOT NULL, priority INT NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_active BOOLEAN NOT NULL, experiment_key VARCHAR(120) DEFAULT NULL, experiment_variant VARCHAR(80) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, target_category_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_85E8297F957CD2E8 ON special_offer (target_category_id)');
        $this->addSql('CREATE INDEX idx_special_offer_active_dates ON special_offer (is_active, starts_at, ends_at)');
        $this->addSql('CREATE INDEX idx_special_offer_placement_priority ON special_offer (placement, priority)');
        $this->addSql('ALTER TABLE special_offer ADD CONSTRAINT FK_85E8297F957CD2E8 FOREIGN KEY (target_category_id) REFERENCES category (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE special_offer DROP CONSTRAINT FK_85E8297F957CD2E8');
        $this->addSql('DROP TABLE special_offer');
    }
}
