<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260823170000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Normalize existing product category strings into category records without data loss';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, slug VARCHAR(140) NOT NULL, icon VARCHAR(100) DEFAULT NULL, is_featured BOOLEAN NOT NULL DEFAULT FALSE, show_in_navigation BOOLEAN NOT NULL DEFAULT TRUE, navigation_position INT NOT NULL DEFAULT 0, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_64C19C1989D9B62 ON category (slug)');
        $this->addSql(<<<'SQL'
            WITH source AS (
                SELECT DISTINCT ON (LOWER(TRIM(category)))
                    TRIM(category) AS name,
                    LOWER(TRIM(category)) AS source_key,
                    TRIM(BOTH '-' FROM REGEXP_REPLACE(LOWER(TRIM(category)), '[^a-z0-9]+', '-', 'g')) AS base_slug
                FROM product
                ORDER BY LOWER(TRIM(category)), id
            ), ranked AS (
                SELECT *, ROW_NUMBER() OVER (PARTITION BY base_slug ORDER BY source_key) AS slug_rank
                FROM source
            )
            INSERT INTO category (name, slug, is_featured, show_in_navigation, navigation_position, created_at, updated_at)
            SELECT name,
                CASE
                    WHEN base_slug = '' THEN 'categorie-' || SUBSTRING(MD5(source_key), 1, 8)
                    WHEN slug_rank = 1 THEN base_slug
                    ELSE base_slug || '-' || SUBSTRING(MD5(source_key), 1, 8)
                END,
                FALSE, TRUE,
                ROW_NUMBER() OVER (ORDER BY name) * 10,
                CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
            FROM ranked
            SQL);
        $this->addSql('ALTER TABLE category ALTER is_featured DROP DEFAULT');
        $this->addSql('ALTER TABLE category ALTER show_in_navigation DROP DEFAULT');
        $this->addSql('ALTER TABLE category ALTER navigation_position DROP DEFAULT');
        $this->addSql('ALTER TABLE product ADD category_id INT DEFAULT NULL');
        $this->addSql('UPDATE product p SET category_id = c.id FROM category c WHERE LOWER(TRIM(p.category)) = LOWER(TRIM(c.name))');
        $this->addSql(<<<'SQL'
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM product WHERE category_id IS NULL) THEN
                    RAISE EXCEPTION 'Category migration failed: at least one product was not associated';
                END IF;
            END $$
            SQL);
        $this->addSql('ALTER TABLE product ALTER category_id SET NOT NULL');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_D34A04AD12469DE2 ON product (category_id)');
        $this->addSql('ALTER TABLE product DROP category');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE product ADD category VARCHAR(100) DEFAULT NULL');
        $this->addSql('UPDATE product p SET category = c.name FROM category c WHERE p.category_id = c.id');
        $this->addSql('ALTER TABLE product ALTER category SET NOT NULL');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04AD12469DE2');
        $this->addSql('DROP INDEX IDX_D34A04AD12469DE2');
        $this->addSql('ALTER TABLE product DROP category_id');
        $this->addSql('DROP TABLE category');
    }
}
