<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260823210000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add persisted customer orders and immutable product snapshots';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE customer_order (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, reference VARCHAR(40) NOT NULL, external_ref VARCHAR(180) DEFAULT NULL, status VARCHAR(40) NOT NULL, total_cents INT NOT NULL, ordered_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id), CONSTRAINT chk_customer_order_total CHECK (total_cents >= 0))");
        $this->addSql('CREATE INDEX IDX_3B1CE6A3A76ED395 ON customer_order (user_id)');
        $this->addSql('CREATE INDEX idx_customer_order_ordered_at ON customer_order (ordered_at)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3B1CE6A3AEA34913 ON customer_order (reference)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3B1CE6A3B445906B ON customer_order (external_ref)');
        $this->addSql('ALTER TABLE customer_order ADD CONSTRAINT fk_customer_order_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE order_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_id INT NOT NULL, product_id INT DEFAULT NULL, product_id_snapshot INT DEFAULT NULL, product_name_snapshot VARCHAR(180) NOT NULL, product_slug_snapshot VARCHAR(190) NOT NULL, quantity INT NOT NULL, unit_price_cents INT NOT NULL, line_total_cents INT NOT NULL, PRIMARY KEY(id), CONSTRAINT chk_order_item_quantity CHECK (quantity > 0), CONSTRAINT chk_order_item_unit_price CHECK (unit_price_cents >= 0), CONSTRAINT chk_order_item_line_total CHECK (line_total_cents >= 0))');
        $this->addSql('CREATE INDEX IDX_52EA1F098D9F6D38 ON order_item (order_id)');
        $this->addSql('CREATE INDEX IDX_52EA1F094584665A ON order_item (product_id)');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES customer_order (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT fk_order_item_product FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE order_item');
        $this->addSql('DROP TABLE customer_order');
    }
}
