<?php
namespace App\Tests\Import;
use App\Entity\Category;use App\Entity\Order;use App\Entity\Product;use App\Entity\Review;use App\Entity\User;use App\Import\ImportManager;use App\Kernel;use Doctrine\ORM\EntityManagerInterface;use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;use Symfony\Component\HttpKernel\KernelInterface;
final class ImportPipelineTest extends KernelTestCase
{
 protected static function createKernel(array $options=[]):KernelInterface{return new Kernel($options['environment']??'test',$options['debug']??true);}
 public function testSyntheticScenarioDryRunIntegrityAndIdempotence():void
 {
  self::bootKernel();$container=static::getContainer();$em=$container->get(EntityManagerInterface::class);$manager=$container->get(ImportManager::class);$suffix=strtolower(bin2hex(random_bytes(5)));$category=(new Category())->setName('Import '.$suffix)->setSlug('import-'.$suffix);$em->persist($category);$em->flush();
  $refs=['user'=>'USR-'.$suffix,'product'=>'PROD-'.$suffix,'order'=>'ORDER-'.$suffix,'review'=>'REVIEW-'.$suffix];$files=[];
  $files['users']=$this->json($suffix,'users',['users'=>[['externalRef'=>$refs['user'],'email'=>$suffix.'@example.test','firstName'=>'Ada','lastName'=>'Fictive','createdAt'=>'2025-01-15T10:00:00+00:00']]]);
  $files['products']=$this->json($suffix,'products',['products'=>[['externalRef'=>$refs['product'],'name'=>'Produit fictif','slug'=>'produit-'.$suffix,'description'=>'Synthétique','priceCents'=>1299,'stock'=>5,'categorySlug'=>$category->getSlug(),'imageUrl'=>null,'isActive'=>true]]]);
  $files['orders']=$this->json($suffix,'orders',['orders'=>[['externalRef'=>$refs['order'],'userExternalRef'=>$refs['user'],'status'=>'completed','orderedAt'=>'2026-03-12T14:35:00+00:00','totalCents'=>2598]],'order_items'=>[['orderExternalRef'=>$refs['order'],'productExternalRef'=>$refs['product'],'productNameSnapshot'=>'Nom historique','productSlugSnapshot'=>'slug-historique','quantity'=>2,'unitPriceCents'=>1299]]]);
  $files['reviews']=$this->json($suffix,'reviews',['reviews'=>[['externalRef'=>$refs['review'],'userExternalRef'=>$refs['user'],'productExternalRef'=>$refs['product'],'rating'=>5,'comment'=>'Avis fictif','createdAt'=>'2026-03-20T09:00:00+00:00']]]);
  $dry=$manager->import('users',$files['users'],true);self::assertSame(1,$dry->getCreated());self::assertNull($em->getRepository(User::class)->findOneBy(['externalRef'=>$refs['user']]));
  foreach(['users','products','orders','reviews'] as $type){$result=$manager->import($type,$files[$type]);self::assertSame(1,$result->getCreated(),$type);self::assertSame(0,$result->getFailed(),$type);}
  $user=$em->getRepository(User::class)->findOneBy(['externalRef'=>$refs['user']]);$product=$em->getRepository(Product::class)->findOneBy(['externalRef'=>$refs['product']]);$order=$em->getRepository(Order::class)->findOneBy(['externalRef'=>$refs['order']]);$review=$em->getRepository(Review::class)->findOneBy(['externalRef'=>$refs['review']]);self::assertNotSame('',$user->getPassword());self::assertEquals(new \DateTimeImmutable('2025-01-15T10:00:00+00:00'),$user->getCreatedAt());self::assertSame(2598,$order->getTotalCents());self::assertSame('Nom historique',$order->getItems()->first()->getProductNameSnapshot());self::assertSame($refs['product'],$order->getItems()->first()->getProductExternalRefSnapshot());self::assertTrue($container->get(\App\Repository\OrderRepository::class)->hasUserPurchasedProduct($user,$product));self::assertEquals(new \DateTimeImmutable('2026-03-20T09:00:00+00:00'),$review->getCreatedAt());
  $password=$user->getPassword();self::assertSame(1,$manager->import('orders',$files['orders'])->getSkipped());$manager->import('users',$files['users']);self::assertSame($password,$user->getPassword());$manager->import('products',$files['products']);$manager->import('reviews',$files['reviews']);self::assertCount(1,$em->getRepository(User::class)->findBy(['externalRef'=>$refs['user']]));self::assertCount(1,$em->getRepository(Product::class)->findBy(['externalRef'=>$refs['product']]));self::assertCount(1,$em->getRepository(Order::class)->findBy(['externalRef'=>$refs['order']]));self::assertCount(1,$em->getRepository(Review::class)->findBy(['externalRef'=>$refs['review']]));
 }
 private function json(string $suffix,string $type,array $data):string{$file=sys_get_temp_dir().'/shopwho-'.$type.'-'.$suffix.'.json';file_put_contents($file,json_encode($data,JSON_THROW_ON_ERROR));return $file;}
}
