<?php
namespace App\Tests\Import;
use App\Entity\Category;use App\Entity\Order;use App\Entity\Product;use App\Entity\Review;use App\Entity\User;use App\Import\ImportManager;use App\Kernel;use Doctrine\ORM\EntityManagerInterface;use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;use Symfony\Component\HttpKernel\KernelInterface;
final class ImportPipelineTest extends KernelTestCase
{
 protected static function createKernel(array $options=[]):KernelInterface{return new Kernel($options['environment']??'test',$options['debug']??true);}
 public function testSyntheticScenarioDryRunIntegrityAndIdempotence():void
 {
  self::bootKernel();$container=static::getContainer();$em=$container->get(EntityManagerInterface::class);$manager=$container->get(ImportManager::class);$suffix=strtolower(bin2hex(random_bytes(5)));$category=(new Category())->setName('Import '.$suffix)->setSlug('import-'.$suffix);$em->persist($category);$em->flush();
  $refs=['user'=>'USR-'.$suffix,'product'=>'PROD-'.$suffix,'order'=>'ORDER-'.$suffix,'review'=>'REVIEW-'.$suffix];$files=[];
  $files['users']=$this->json($suffix,'users',['users'=>[['externalRef'=>$refs['user'],'email'=>$suffix.'@example.test','firstName'=>'Ada','lastName'=>'Fictive','createdAt'=>'2025-01-15T10:00:00+00:00']]]);
  $files['products']=$this->json($suffix,'products',['products'=>[['externalRef'=>$refs['product'],'name'=>'Produit fictif','slug'=>'produit-'.$suffix,'description'=>'Synthétique','priceCents'=>1299,'stock'=>5,'categorySlug'=>$category->getSlug(),'imageUrl'=>null,'isActive'=>true]]]);
  $files['orders']=$this->json($suffix,'orders',['orders'=>[['externalRef'=>$refs['order'],'userExternalRef'=>$refs['user'],'status'=>'completed','orderedAt'=>'2026-03-12T14:35:00+00:00','totalCents'=>2598]],'order_items'=>[['orderExternalRef'=>$refs['order'],'productExternalRef'=>$refs['product'],'productNameSnapshot'=>'Nom historique','productSlugSnapshot'=>'slug-historique','quantity'=>2,'unitPriceCents'=>1299]]]);
  $files['reviews']=$this->json($suffix,'reviews',['reviews'=>[['externalRef'=>$refs['review'],'userExternalRef'=>$refs['user'],'productExternalRef'=>$refs['product'],'rating'=>5,'comment'=>'Avis fictif','createdAt'=>'2026-03-20T09:00:00+00:00']]]);
  $dry=$manager->import('users',$files['users'],true);self::assertSame(1,$dry->getCreated());self::assertNull($em->getRepository(User::class)->findOneBy(['externalRef'=>$refs['user']]));
  foreach(['users','products','orders','reviews'] as $type){$result=$manager->import($type,$files[$type]);self::assertSame(1,$result->getCreated(),$type);self::assertSame(0,$result->getFailed(),$type);}
  $user=$em->getRepository(User::class)->findOneBy(['externalRef'=>$refs['user']]);$product=$em->getRepository(Product::class)->findOneBy(['externalRef'=>$refs['product']]);$order=$em->getRepository(Order::class)->findOneBy(['externalRef'=>$refs['order']]);$review=$em->getRepository(Review::class)->findOneBy(['externalRef'=>$refs['review']]);self::assertNotSame('',$user->getPassword());self::assertEquals(new \DateTimeImmutable('2025-01-15T10:00:00+00:00'),$user->getCreatedAt());self::assertSame(2598,$order->getTotalCents());self::assertSame('Nom historique',$order->getItems()->first()->getProductNameSnapshot());self::assertSame($refs['product'],$order->getItems()->first()->getProductExternalRefSnapshot());self::assertTrue($container->get(\App\Repository\OrderRepository::class)->hasUserPurchasedProduct($user,$product));self::assertEquals(new \DateTimeImmutable('2026-03-20T09:00:00+00:00'),$review->getCreatedAt());
  $password=$user->getPassword();self::assertSame(1,$manager->import('orders',$files['orders'])->getSkipped());$manager->import('users',$files['users']);self::assertSame($password,$user->getPassword());$manager->import('products',$files['products']);$manager->import('reviews',$files['reviews']);self::assertCount(1,$em->getRepository(User::class)->findBy(['externalRef'=>$refs['user']]));self::assertCount(1,$em->getRepository(Product::class)->findBy(['externalRef'=>$refs['product']]));self::assertCount(1,$em->getRepository(Order::class)->findBy(['externalRef'=>$refs['order']]));self::assertCount(1,$em->getRepository(Review::class)->findBy(['externalRef'=>$refs['review']]));
 }
 public function testPartialProductParsingFailureContinuesAndMatchesDryRunCounts():void
 {
  self::bootKernel();$container=static::getContainer();$em=$container->get(EntityManagerInterface::class);$manager=$container->get(ImportManager::class);$suffix=strtolower(bin2hex(random_bytes(5)));$category=(new Category())->setName('Partial '.$suffix)->setSlug('partial-'.$suffix);$em->persist($category);$em->flush();$refs=['PROD-A-'.$suffix,'PROD-B-'.$suffix,'PROD-C-'.$suffix];
  $file=$this->json($suffix,'partial-products',['products'=>[['externalRef'=>$refs[0],'name'=>'One','slug'=>'one-'.$suffix,'description'=>'One','priceCents'=>100,'stock'=>1,'categorySlug'=>$category->getSlug(),'imageUrl'=>null,'isActive'=>true],['externalRef'=>$refs[1],'name'=>'Bad','slug'=>'bad-'.$suffix,'description'=>'Bad','priceCents'=>'12abc','stock'=>1,'categorySlug'=>$category->getSlug(),'imageUrl'=>null,'isActive'=>true],['externalRef'=>$refs[2],'name'=>'Three','slug'=>'three-'.$suffix,'description'=>'Three','priceCents'=>300,'stock'=>1,'categorySlug'=>$category->getSlug(),'imageUrl'=>null,'isActive'=>true]]]);
  $dry=$manager->import('products',$file,true);self::assertSame([3,2,1],[$dry->getTotal(),$dry->getCreated(),$dry->getFailed()]);foreach($refs as $ref)self::assertNull($em->getRepository(Product::class)->findOneBy(['externalRef'=>$ref]));
  $result=$manager->import('products',$file);self::assertSame([3,2,1],[$result->getTotal(),$result->getCreated(),$result->getFailed()]);self::assertSame(2,$result->getErrors()[0]->record);self::assertSame($refs[1],$result->getErrors()[0]->externalRef);self::assertNotNull($em->getRepository(Product::class)->findOneBy(['externalRef'=>$refs[0]]));self::assertNull($em->getRepository(Product::class)->findOneBy(['externalRef'=>$refs[1]]));self::assertNotNull($em->getRepository(Product::class)->findOneBy(['externalRef'=>$refs[2]]));
 }
 public function testInvalidOrderItemFailsOnlyItsOrder():void
 {
  self::bootKernel();$container=static::getContainer();$em=$container->get(EntityManagerInterface::class);$manager=$container->get(ImportManager::class);$suffix=strtolower(bin2hex(random_bytes(5)));$user=$this->user($em,$suffix);$a='ORDER-A-'.$suffix;$b='ORDER-B-'.$suffix;$file=$this->json($suffix,'partial-orders',['orders'=>[['externalRef'=>$a,'userExternalRef'=>$user->getExternalRef(),'status'=>'completed','orderedAt'=>null,'totalCents'=>100],['externalRef'=>$b,'userExternalRef'=>$user->getExternalRef(),'status'=>'completed','orderedAt'=>null,'totalCents'=>200]],'order_items'=>[['orderExternalRef'=>$a,'productExternalRef'=>null,'productNameSnapshot'=>'A','productSlugSnapshot'=>'a','quantity'=>'abc','unitPriceCents'=>100],['orderExternalRef'=>$b,'productExternalRef'=>null,'productNameSnapshot'=>'B','productSlugSnapshot'=>'b','quantity'=>2,'unitPriceCents'=>100]]]);
  $result=$manager->import('orders',$file);self::assertSame([2,1,1],[$result->getTotal(),$result->getCreated(),$result->getFailed()]);self::assertSame(1,$result->getErrors()[0]->record);self::assertSame($a,$result->getErrors()[0]->externalRef);self::assertNull($em->getRepository(Order::class)->findOneBy(['externalRef'=>$a]));self::assertNotNull($em->getRepository(Order::class)->findOneBy(['externalRef'=>$b]));
 }
 public function testOrphanOrderItemIsExplicitlyReported():void
 {
  self::bootKernel();$container=static::getContainer();$em=$container->get(EntityManagerInterface::class);$manager=$container->get(ImportManager::class);$suffix=strtolower(bin2hex(random_bytes(5)));$user=$this->user($em,$suffix);$orderRef='ORDER-'.$suffix;$orphan='ORDER-404-'.$suffix;$file=$this->json($suffix,'orphan-orders',['orders'=>[['externalRef'=>$orderRef,'userExternalRef'=>$user->getExternalRef(),'status'=>'completed','orderedAt'=>null,'totalCents'=>100]],'order_items'=>[['orderExternalRef'=>$orderRef,'productExternalRef'=>null,'productNameSnapshot'=>'Valid','productSlugSnapshot'=>'valid','quantity'=>1,'unitPriceCents'=>100],['orderExternalRef'=>$orphan,'productExternalRef'=>null,'productNameSnapshot'=>'Orphan','productSlugSnapshot'=>'orphan','quantity'=>1,'unitPriceCents'=>100]]]);
  $result=$manager->import('orders',$file);self::assertSame([2,1,1],[$result->getTotal(),$result->getCreated(),$result->getFailed()]);self::assertSame(2,$result->getErrors()[0]->record);self::assertSame($orphan,$result->getErrors()[0]->externalRef);self::assertStringContainsString('Unknown orderExternalRef',$result->getErrors()[0]->message);
 }
 public function testSchemaLengthsFailValidationBeforePersistence():void
 {
  self::bootKernel();$container=static::getContainer();$em=$container->get(EntityManagerInterface::class);$manager=$container->get(ImportManager::class);$suffix=strtolower(bin2hex(random_bytes(5)));$tooLong=str_repeat('x',181);$userFile=$this->json($suffix,'long-user',['users'=>[['externalRef'=>$tooLong,'email'=>$suffix.'@example.test','firstName'=>null,'lastName'=>null,'createdAt'=>null]]]);$userResult=$manager->import('users',$userFile);self::assertSame([1,0,1],[$userResult->getTotal(),$userResult->getCreated(),$userResult->getFailed()]);self::assertStringContainsString('externalRef',$userResult->getErrors()[0]->message);
  $user=$this->user($em,'snapshot-'.$suffix);$orderRef='ORDER-SNAPSHOT-'.$suffix;$orderFile=$this->json($suffix,'long-snapshot',['orders'=>[['externalRef'=>$orderRef,'userExternalRef'=>$user->getExternalRef(),'status'=>'completed','orderedAt'=>null,'totalCents'=>100]],'order_items'=>[['orderExternalRef'=>$orderRef,'productExternalRef'=>null,'productNameSnapshot'=>$tooLong,'productSlugSnapshot'=>'snapshot','quantity'=>1,'unitPriceCents'=>100]]]);$orderResult=$manager->import('orders',$orderFile);self::assertSame([1,0,1],[$orderResult->getTotal(),$orderResult->getCreated(),$orderResult->getFailed()]);self::assertStringContainsString('productNameSnapshot',$orderResult->getErrors()[0]->message);self::assertNull($em->getRepository(Order::class)->findOneBy(['externalRef'=>$orderRef]));
 }
 public function testOrderStatusLabels():void
 {
  $user=new User();$simulated=new Order($user,'SIM-1',0);self::assertSame('Terminée (simulation)',$simulated->getStatusLabel());self::assertSame('Terminée',Order::import($user,'IMP-1','completed',0)->getStatusLabel());self::assertSame('Annulée',Order::import($user,'IMP-2','cancelled',0)->getStatusLabel());self::assertSame('Remboursée',Order::import($user,'IMP-3','refunded',0)->getStatusLabel());
 }
 private function user(EntityManagerInterface $em,string $suffix):User{$user=(new User())->setEmail($suffix.'@example.test')->setExternalRef('USR-'.$suffix)->setPassword('not-used');$em->persist($user);$em->flush();return $user;}
 private function json(string $suffix,string $type,array $data):string{$file=sys_get_temp_dir().'/shopwho-'.$type.'-'.$suffix.'.json';file_put_contents($file,json_encode($data,JSON_THROW_ON_ERROR));return $file;}
}
